<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ECO.WebApi.Migrators.MSSQL</RootNamespace>
		<AssemblyName>ECO.WebApi.Migrators.MSSQL</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Infrastructure\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>

</Project>
