version: '3.8'

name: eco_application

networks:
  econetwork:
    driver: bridge

services:
  ecodb:
    container_name: eco-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_Password}
    networks:
      - econetwork

  eco.api:
    container_name: eco-host-api
    build: 
      context: ../
      dockerfile: docker/eco-api.Dockerfile
    image: ${DOCKER_REGISTRY-}eco_api
    environment:
      -  ConnectionStrings__ConnectionString=${ConnectionStrings_Default}
    ports:
      - "${ASPNETCORE_API_PORT}:80"
    depends_on:
      - ecodb
    networks:
      - econetwork
    entrypoint: ["dotnet", "ECO.WebApi.Host.dll"]
