<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ECO.WebApi.Domain</RootNamespace>
		<AssemblyName>ECO.WebApi.Domain</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NewId" Version="4.0.1" />
	</ItemGroup>
</Project>
